import type { Locale } from "@izbri/contracts";

export const messages = {
  en: {
    title: "Izbri Projects", subtitle: "Things I have designed, built, and keep running.",
    filter: "Filter projects", sort: "Sort projects", language: "Cambiar a español", theme: "Change color theme",
    all: "All", status: "Status", technology: "Technology", resource: "Resource type", curated: "Curated", name: "Name", uptime: "Uptime", newest: "Newest",
    application: "Application", service: "Service", online: "Online", degraded: "Degraded", offline: "Offline", collecting: "Collecting data", unknown: "Not monitored",
    daysRunning: "days running", response: "response", uptime30: "30-day uptime", stack: "Built with", empty: "No projects match these filters.", emptyLead: "Published work will appear here soon.",
    unavailable: "The project feed is temporarily unavailable.", sampleData: "Sample projects are shown until the first real project is published.", close: "Close details", viewDetails: "View project details", openApp: "Open live application", caseStudy: "Read case study", repository: "View repository",
    overview: "Overview", reliability: "Reliability", lastCheck: "Last checked", currentStreak: "Current streak", latency: "Response time", period24h: "24 hours", period7d: "7 days", period30d: "30 days", allTime: "All time", noHistory: "Collecting history", collectingExplanation: "The first check usually arrives within one minute. Uptime and latency become more representative with every check.",
    previewOnly: "Preview only — these changes are not saved or published.", returnToEditor: "Return to editor",
    footer: "Designed and monitored from the Canary Islands.", clear: "Clear filters", incidents: "Recent incidents", noIncidents: "No confirmed incidents recorded.", ongoing: "Ongoing", recovered: "Recovered", maintenance: "Maintenance", deploying: "Deployment in progress", lastDeployed: "Last successful deployment", lastSynchronized: "Last synchronized", activeIncident: "Active incident", incidentStarted: "Confirmed outage since", noticeMaintenance: "Maintenance in progress", noticeRestart: "Restart in progress", noticeUpdate: "Update in progress", reportProblem: "Report a problem", contactOwner: "Contact the owner", incidentUserPrompt: "Do you use this app? Tell me what you are seeing.", build: "Build", branch: "Branch", commit: "Commit", coolifyState: "Coolify state", sentinel: "Sentinel", sentinelMetrics: "CPU/RAM collection active", sentinelAgent: "Agent connected", sentinelOff: "Disabled", sentinelPulse: "Sentinel pulse", previousSlide: "Previous project image", nextSlide: "Next project image", slides: "Project carousel slides", slide: "Go to slide",
  },
  es: {
    title: "Izbri Proyectos", subtitle: "Cosas que he diseñado, construido y mantengo funcionando.",
    filter: "Filtrar proyectos", sort: "Ordenar proyectos", language: "Switch to English", theme: "Cambiar tema de color",
    all: "Todos", status: "Estado", technology: "Tecnología", resource: "Tipo de recurso", curated: "Selección", name: "Nombre", uptime: "Disponibilidad", newest: "Más recientes",
    application: "Aplicación", service: "Servicio", online: "En línea", degraded: "Degradado", offline: "Fuera de línea", collecting: "Recopilando datos", unknown: "Sin monitorizar",
    daysRunning: "días funcionando", response: "respuesta", uptime30: "Disponibilidad 30 días", stack: "Creado con", empty: "Ningún proyecto coincide con los filtros.", emptyLead: "El trabajo publicado aparecerá aquí pronto.",
    unavailable: "El listado no está disponible temporalmente.", sampleData: "Se muestran proyectos de ejemplo hasta que se publique el primer proyecto real.", close: "Cerrar detalles", viewDetails: "Ver detalles del proyecto", openApp: "Abrir aplicación", caseStudy: "Leer caso de estudio", repository: "Ver repositorio",
    overview: "Resumen", reliability: "Fiabilidad", lastCheck: "Última comprobación", currentStreak: "Racha actual", latency: "Tiempo de respuesta", period24h: "24 horas", period7d: "7 días", period30d: "30 días", allTime: "Todo el tiempo", noHistory: "Recopilando historial", collectingExplanation: "La primera comprobación suele llegar en menos de un minuto. La disponibilidad y la latencia son más representativas con cada comprobación.",
    previewOnly: "Solo vista previa: estos cambios no están guardados ni publicados.", returnToEditor: "Volver al editor",
    footer: "Diseñado y monitorizado desde las Islas Canarias.", clear: "Limpiar filtros", incidents: "Incidentes recientes", noIncidents: "No hay incidentes confirmados.", ongoing: "En curso", recovered: "Recuperado", maintenance: "Mantenimiento", deploying: "Despliegue en curso", lastDeployed: "Último despliegue correcto", lastSynchronized: "Última sincronización", activeIncident: "Incidente activo", incidentStarted: "Caída confirmada desde", noticeMaintenance: "Mantenimiento en curso", noticeRestart: "Reinicio en curso", noticeUpdate: "Actualización en curso", reportProblem: "Informar de un problema", contactOwner: "Contactar con el propietario", incidentUserPrompt: "¿Usas esta aplicación? Cuéntame qué estás viendo.", build: "Compilación", branch: "Rama", commit: "Commit", coolifyState: "Estado en Coolify", sentinel: "Sentinel", sentinelMetrics: "Recopilación de CPU/RAM activa", sentinelAgent: "Agente conectado", sentinelOff: "Desactivado", sentinelPulse: "Pulso de Sentinel", previousSlide: "Imagen anterior del proyecto", nextSlide: "Imagen siguiente del proyecto", slides: "Diapositivas del proyecto", slide: "Ir a la diapositiva",
  },
} as const;

export function getMessages(locale: Locale) { return messages[locale]; }
